# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/zachm/OneDrive/Desktop/Moryx_engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/zachm/OneDrive/Desktop/Moryx_engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/zachm/OneDrive/Desktop/Moryx_engine/CMakeFiles /mnt/c/Users/zachm/OneDrive/Desktop/Moryx_engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/zachm/OneDrive/Desktop/Moryx_engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Moryx_Engine

# Build rule for target.
Moryx_Engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Moryx_Engine
.PHONY : Moryx_Engine

# fast build rule for target.
Moryx_Engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/build
.PHONY : Moryx_Engine/fast

#=============================================================================
# Target rules for targets named FastNoise

# Build rule for target.
FastNoise: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FastNoise
.PHONY : FastNoise

# fast build rule for target.
FastNoise/fast:
	$(MAKE) $(MAKESILENT) -f lib/FastNoise2/src/CMakeFiles/FastNoise.dir/build.make lib/FastNoise2/src/CMakeFiles/FastNoise.dir/build
.PHONY : FastNoise/fast

src/App/app_window.o: src/App/app_window.cpp.o
.PHONY : src/App/app_window.o

# target to build an object file
src/App/app_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/App/app_window.cpp.o
.PHONY : src/App/app_window.cpp.o

src/App/app_window.i: src/App/app_window.cpp.i
.PHONY : src/App/app_window.i

# target to preprocess a source file
src/App/app_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/App/app_window.cpp.i
.PHONY : src/App/app_window.cpp.i

src/App/app_window.s: src/App/app_window.cpp.s
.PHONY : src/App/app_window.s

# target to generate assembly for a file
src/App/app_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/App/app_window.cpp.s
.PHONY : src/App/app_window.cpp.s

src/App/main.o: src/App/main.cpp.o
.PHONY : src/App/main.o

# target to build an object file
src/App/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/App/main.cpp.o
.PHONY : src/App/main.cpp.o

src/App/main.i: src/App/main.cpp.i
.PHONY : src/App/main.i

# target to preprocess a source file
src/App/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/App/main.cpp.i
.PHONY : src/App/main.cpp.i

src/App/main.s: src/App/main.cpp.s
.PHONY : src/App/main.s

# target to generate assembly for a file
src/App/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/App/main.cpp.s
.PHONY : src/App/main.cpp.s

src/Engine/entities/voxel_components.o: src/Engine/entities/voxel_components.cpp.o
.PHONY : src/Engine/entities/voxel_components.o

# target to build an object file
src/Engine/entities/voxel_components.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/entities/voxel_components.cpp.o
.PHONY : src/Engine/entities/voxel_components.cpp.o

src/Engine/entities/voxel_components.i: src/Engine/entities/voxel_components.cpp.i
.PHONY : src/Engine/entities/voxel_components.i

# target to preprocess a source file
src/Engine/entities/voxel_components.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/entities/voxel_components.cpp.i
.PHONY : src/Engine/entities/voxel_components.cpp.i

src/Engine/entities/voxel_components.s: src/Engine/entities/voxel_components.cpp.s
.PHONY : src/Engine/entities/voxel_components.s

# target to generate assembly for a file
src/Engine/entities/voxel_components.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/entities/voxel_components.cpp.s
.PHONY : src/Engine/entities/voxel_components.cpp.s

src/Engine/graphics_engine/constant_buffer/constant_buffer.o: src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.o
.PHONY : src/Engine/graphics_engine/constant_buffer/constant_buffer.o

# target to build an object file
src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.o
.PHONY : src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.o

src/Engine/graphics_engine/constant_buffer/constant_buffer.i: src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.i
.PHONY : src/Engine/graphics_engine/constant_buffer/constant_buffer.i

# target to preprocess a source file
src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.i
.PHONY : src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.i

src/Engine/graphics_engine/constant_buffer/constant_buffer.s: src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.s
.PHONY : src/Engine/graphics_engine/constant_buffer/constant_buffer.s

# target to generate assembly for a file
src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.s
.PHONY : src/Engine/graphics_engine/constant_buffer/constant_buffer.cpp.s

src/Engine/graphics_engine/device_context/device_context.o: src/Engine/graphics_engine/device_context/device_context.cpp.o
.PHONY : src/Engine/graphics_engine/device_context/device_context.o

# target to build an object file
src/Engine/graphics_engine/device_context/device_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/device_context/device_context.cpp.o
.PHONY : src/Engine/graphics_engine/device_context/device_context.cpp.o

src/Engine/graphics_engine/device_context/device_context.i: src/Engine/graphics_engine/device_context/device_context.cpp.i
.PHONY : src/Engine/graphics_engine/device_context/device_context.i

# target to preprocess a source file
src/Engine/graphics_engine/device_context/device_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/device_context/device_context.cpp.i
.PHONY : src/Engine/graphics_engine/device_context/device_context.cpp.i

src/Engine/graphics_engine/device_context/device_context.s: src/Engine/graphics_engine/device_context/device_context.cpp.s
.PHONY : src/Engine/graphics_engine/device_context/device_context.s

# target to generate assembly for a file
src/Engine/graphics_engine/device_context/device_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/device_context/device_context.cpp.s
.PHONY : src/Engine/graphics_engine/device_context/device_context.cpp.s

src/Engine/graphics_engine/graphics_engine.o: src/Engine/graphics_engine/graphics_engine.cpp.o
.PHONY : src/Engine/graphics_engine/graphics_engine.o

# target to build an object file
src/Engine/graphics_engine/graphics_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/graphics_engine.cpp.o
.PHONY : src/Engine/graphics_engine/graphics_engine.cpp.o

src/Engine/graphics_engine/graphics_engine.i: src/Engine/graphics_engine/graphics_engine.cpp.i
.PHONY : src/Engine/graphics_engine/graphics_engine.i

# target to preprocess a source file
src/Engine/graphics_engine/graphics_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/graphics_engine.cpp.i
.PHONY : src/Engine/graphics_engine/graphics_engine.cpp.i

src/Engine/graphics_engine/graphics_engine.s: src/Engine/graphics_engine/graphics_engine.cpp.s
.PHONY : src/Engine/graphics_engine/graphics_engine.s

# target to generate assembly for a file
src/Engine/graphics_engine/graphics_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/graphics_engine.cpp.s
.PHONY : src/Engine/graphics_engine/graphics_engine.cpp.s

src/Engine/graphics_engine/index_buffer/index_buffer.o: src/Engine/graphics_engine/index_buffer/index_buffer.cpp.o
.PHONY : src/Engine/graphics_engine/index_buffer/index_buffer.o

# target to build an object file
src/Engine/graphics_engine/index_buffer/index_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/index_buffer/index_buffer.cpp.o
.PHONY : src/Engine/graphics_engine/index_buffer/index_buffer.cpp.o

src/Engine/graphics_engine/index_buffer/index_buffer.i: src/Engine/graphics_engine/index_buffer/index_buffer.cpp.i
.PHONY : src/Engine/graphics_engine/index_buffer/index_buffer.i

# target to preprocess a source file
src/Engine/graphics_engine/index_buffer/index_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/index_buffer/index_buffer.cpp.i
.PHONY : src/Engine/graphics_engine/index_buffer/index_buffer.cpp.i

src/Engine/graphics_engine/index_buffer/index_buffer.s: src/Engine/graphics_engine/index_buffer/index_buffer.cpp.s
.PHONY : src/Engine/graphics_engine/index_buffer/index_buffer.s

# target to generate assembly for a file
src/Engine/graphics_engine/index_buffer/index_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/index_buffer/index_buffer.cpp.s
.PHONY : src/Engine/graphics_engine/index_buffer/index_buffer.cpp.s

src/Engine/graphics_engine/pixel_shader/pixel_shader.o: src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.o
.PHONY : src/Engine/graphics_engine/pixel_shader/pixel_shader.o

# target to build an object file
src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.o
.PHONY : src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.o

src/Engine/graphics_engine/pixel_shader/pixel_shader.i: src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.i
.PHONY : src/Engine/graphics_engine/pixel_shader/pixel_shader.i

# target to preprocess a source file
src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.i
.PHONY : src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.i

src/Engine/graphics_engine/pixel_shader/pixel_shader.s: src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.s
.PHONY : src/Engine/graphics_engine/pixel_shader/pixel_shader.s

# target to generate assembly for a file
src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.s
.PHONY : src/Engine/graphics_engine/pixel_shader/pixel_shader.cpp.s

src/Engine/graphics_engine/render_system/render_system.o: src/Engine/graphics_engine/render_system/render_system.cpp.o
.PHONY : src/Engine/graphics_engine/render_system/render_system.o

# target to build an object file
src/Engine/graphics_engine/render_system/render_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/render_system/render_system.cpp.o
.PHONY : src/Engine/graphics_engine/render_system/render_system.cpp.o

src/Engine/graphics_engine/render_system/render_system.i: src/Engine/graphics_engine/render_system/render_system.cpp.i
.PHONY : src/Engine/graphics_engine/render_system/render_system.i

# target to preprocess a source file
src/Engine/graphics_engine/render_system/render_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/render_system/render_system.cpp.i
.PHONY : src/Engine/graphics_engine/render_system/render_system.cpp.i

src/Engine/graphics_engine/render_system/render_system.s: src/Engine/graphics_engine/render_system/render_system.cpp.s
.PHONY : src/Engine/graphics_engine/render_system/render_system.s

# target to generate assembly for a file
src/Engine/graphics_engine/render_system/render_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/render_system/render_system.cpp.s
.PHONY : src/Engine/graphics_engine/render_system/render_system.cpp.s

src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.o: src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.o

# target to build an object file
src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.o

src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.i: src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.i

# target to preprocess a source file
src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.i

src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.s: src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.s

# target to generate assembly for a file
src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.cpp.s

src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.o: src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.o

# target to build an object file
src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.o

src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.i: src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.i

# target to preprocess a source file
src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.i

src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.s: src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.s

# target to generate assembly for a file
src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.cpp.s

src/Engine/graphics_engine/resource_manager/resource.o: src/Engine/graphics_engine/resource_manager/resource.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/resource.o

# target to build an object file
src/Engine/graphics_engine/resource_manager/resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/resource.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/resource.cpp.o

src/Engine/graphics_engine/resource_manager/resource.i: src/Engine/graphics_engine/resource_manager/resource.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/resource.i

# target to preprocess a source file
src/Engine/graphics_engine/resource_manager/resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/resource.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/resource.cpp.i

src/Engine/graphics_engine/resource_manager/resource.s: src/Engine/graphics_engine/resource_manager/resource.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/resource.s

# target to generate assembly for a file
src/Engine/graphics_engine/resource_manager/resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/resource.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/resource.cpp.s

src/Engine/graphics_engine/resource_manager/resource_manager.o: src/Engine/graphics_engine/resource_manager/resource_manager.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/resource_manager.o

# target to build an object file
src/Engine/graphics_engine/resource_manager/resource_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/resource_manager.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/resource_manager.cpp.o

src/Engine/graphics_engine/resource_manager/resource_manager.i: src/Engine/graphics_engine/resource_manager/resource_manager.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/resource_manager.i

# target to preprocess a source file
src/Engine/graphics_engine/resource_manager/resource_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/resource_manager.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/resource_manager.cpp.i

src/Engine/graphics_engine/resource_manager/resource_manager.s: src/Engine/graphics_engine/resource_manager/resource_manager.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/resource_manager.s

# target to generate assembly for a file
src/Engine/graphics_engine/resource_manager/resource_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/resource_manager.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/resource_manager.cpp.s

src/Engine/graphics_engine/resource_manager/texture_manager/texture.o: src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture.o

# target to build an object file
src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.o

src/Engine/graphics_engine/resource_manager/texture_manager/texture.i: src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture.i

# target to preprocess a source file
src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.i

src/Engine/graphics_engine/resource_manager/texture_manager/texture.s: src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture.s

# target to generate assembly for a file
src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture.cpp.s

src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.o: src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.o

# target to build an object file
src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.o
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.o

src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.i: src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.i

# target to preprocess a source file
src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.i
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.i

src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.s: src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.s

# target to generate assembly for a file
src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.s
.PHONY : src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.cpp.s

src/Engine/graphics_engine/swapchain/swapchain.o: src/Engine/graphics_engine/swapchain/swapchain.cpp.o
.PHONY : src/Engine/graphics_engine/swapchain/swapchain.o

# target to build an object file
src/Engine/graphics_engine/swapchain/swapchain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/swapchain/swapchain.cpp.o
.PHONY : src/Engine/graphics_engine/swapchain/swapchain.cpp.o

src/Engine/graphics_engine/swapchain/swapchain.i: src/Engine/graphics_engine/swapchain/swapchain.cpp.i
.PHONY : src/Engine/graphics_engine/swapchain/swapchain.i

# target to preprocess a source file
src/Engine/graphics_engine/swapchain/swapchain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/swapchain/swapchain.cpp.i
.PHONY : src/Engine/graphics_engine/swapchain/swapchain.cpp.i

src/Engine/graphics_engine/swapchain/swapchain.s: src/Engine/graphics_engine/swapchain/swapchain.cpp.s
.PHONY : src/Engine/graphics_engine/swapchain/swapchain.s

# target to generate assembly for a file
src/Engine/graphics_engine/swapchain/swapchain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/swapchain/swapchain.cpp.s
.PHONY : src/Engine/graphics_engine/swapchain/swapchain.cpp.s

src/Engine/graphics_engine/vertex_buffer/vertex_buffer.o: src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.o
.PHONY : src/Engine/graphics_engine/vertex_buffer/vertex_buffer.o

# target to build an object file
src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.o
.PHONY : src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.o

src/Engine/graphics_engine/vertex_buffer/vertex_buffer.i: src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.i
.PHONY : src/Engine/graphics_engine/vertex_buffer/vertex_buffer.i

# target to preprocess a source file
src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.i
.PHONY : src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.i

src/Engine/graphics_engine/vertex_buffer/vertex_buffer.s: src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.s
.PHONY : src/Engine/graphics_engine/vertex_buffer/vertex_buffer.s

# target to generate assembly for a file
src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.s
.PHONY : src/Engine/graphics_engine/vertex_buffer/vertex_buffer.cpp.s

src/Engine/graphics_engine/vertex_shader/vertex_shader.o: src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.o
.PHONY : src/Engine/graphics_engine/vertex_shader/vertex_shader.o

# target to build an object file
src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.o
.PHONY : src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.o

src/Engine/graphics_engine/vertex_shader/vertex_shader.i: src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.i
.PHONY : src/Engine/graphics_engine/vertex_shader/vertex_shader.i

# target to preprocess a source file
src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.i
.PHONY : src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.i

src/Engine/graphics_engine/vertex_shader/vertex_shader.s: src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.s
.PHONY : src/Engine/graphics_engine/vertex_shader/vertex_shader.s

# target to generate assembly for a file
src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.s
.PHONY : src/Engine/graphics_engine/vertex_shader/vertex_shader.cpp.s

src/Engine/input_system/input_system.o: src/Engine/input_system/input_system.cpp.o
.PHONY : src/Engine/input_system/input_system.o

# target to build an object file
src/Engine/input_system/input_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/input_system/input_system.cpp.o
.PHONY : src/Engine/input_system/input_system.cpp.o

src/Engine/input_system/input_system.i: src/Engine/input_system/input_system.cpp.i
.PHONY : src/Engine/input_system/input_system.i

# target to preprocess a source file
src/Engine/input_system/input_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/input_system/input_system.cpp.i
.PHONY : src/Engine/input_system/input_system.cpp.i

src/Engine/input_system/input_system.s: src/Engine/input_system/input_system.cpp.s
.PHONY : src/Engine/input_system/input_system.s

# target to generate assembly for a file
src/Engine/input_system/input_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/input_system/input_system.cpp.s
.PHONY : src/Engine/input_system/input_system.cpp.s

src/Engine/physics/physics.o: src/Engine/physics/physics.cpp.o
.PHONY : src/Engine/physics/physics.o

# target to build an object file
src/Engine/physics/physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/physics/physics.cpp.o
.PHONY : src/Engine/physics/physics.cpp.o

src/Engine/physics/physics.i: src/Engine/physics/physics.cpp.i
.PHONY : src/Engine/physics/physics.i

# target to preprocess a source file
src/Engine/physics/physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/physics/physics.cpp.i
.PHONY : src/Engine/physics/physics.cpp.i

src/Engine/physics/physics.s: src/Engine/physics/physics.cpp.s
.PHONY : src/Engine/physics/physics.s

# target to generate assembly for a file
src/Engine/physics/physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/physics/physics.cpp.s
.PHONY : src/Engine/physics/physics.cpp.s

src/Engine/windowing/window.o: src/Engine/windowing/window.cpp.o
.PHONY : src/Engine/windowing/window.o

# target to build an object file
src/Engine/windowing/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/windowing/window.cpp.o
.PHONY : src/Engine/windowing/window.cpp.o

src/Engine/windowing/window.i: src/Engine/windowing/window.cpp.i
.PHONY : src/Engine/windowing/window.i

# target to preprocess a source file
src/Engine/windowing/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/windowing/window.cpp.i
.PHONY : src/Engine/windowing/window.cpp.i

src/Engine/windowing/window.s: src/Engine/windowing/window.cpp.s
.PHONY : src/Engine/windowing/window.s

# target to generate assembly for a file
src/Engine/windowing/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Moryx_Engine.dir/build.make CMakeFiles/Moryx_Engine.dir/src/Engine/windowing/window.cpp.s
.PHONY : src/Engine/windowing/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FastNoise"
	@echo "... Moryx_Engine"
	@echo "... src/App/app_window.o"
	@echo "... src/App/app_window.i"
	@echo "... src/App/app_window.s"
	@echo "... src/App/main.o"
	@echo "... src/App/main.i"
	@echo "... src/App/main.s"
	@echo "... src/Engine/entities/voxel_components.o"
	@echo "... src/Engine/entities/voxel_components.i"
	@echo "... src/Engine/entities/voxel_components.s"
	@echo "... src/Engine/graphics_engine/constant_buffer/constant_buffer.o"
	@echo "... src/Engine/graphics_engine/constant_buffer/constant_buffer.i"
	@echo "... src/Engine/graphics_engine/constant_buffer/constant_buffer.s"
	@echo "... src/Engine/graphics_engine/device_context/device_context.o"
	@echo "... src/Engine/graphics_engine/device_context/device_context.i"
	@echo "... src/Engine/graphics_engine/device_context/device_context.s"
	@echo "... src/Engine/graphics_engine/graphics_engine.o"
	@echo "... src/Engine/graphics_engine/graphics_engine.i"
	@echo "... src/Engine/graphics_engine/graphics_engine.s"
	@echo "... src/Engine/graphics_engine/index_buffer/index_buffer.o"
	@echo "... src/Engine/graphics_engine/index_buffer/index_buffer.i"
	@echo "... src/Engine/graphics_engine/index_buffer/index_buffer.s"
	@echo "... src/Engine/graphics_engine/pixel_shader/pixel_shader.o"
	@echo "... src/Engine/graphics_engine/pixel_shader/pixel_shader.i"
	@echo "... src/Engine/graphics_engine/pixel_shader/pixel_shader.s"
	@echo "... src/Engine/graphics_engine/render_system/render_system.o"
	@echo "... src/Engine/graphics_engine/render_system/render_system.i"
	@echo "... src/Engine/graphics_engine/render_system/render_system.s"
	@echo "... src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.o"
	@echo "... src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.i"
	@echo "... src/Engine/graphics_engine/resource_manager/mesh_manager/mesh.s"
	@echo "... src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.o"
	@echo "... src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.i"
	@echo "... src/Engine/graphics_engine/resource_manager/mesh_manager/mesh_manager.s"
	@echo "... src/Engine/graphics_engine/resource_manager/resource.o"
	@echo "... src/Engine/graphics_engine/resource_manager/resource.i"
	@echo "... src/Engine/graphics_engine/resource_manager/resource.s"
	@echo "... src/Engine/graphics_engine/resource_manager/resource_manager.o"
	@echo "... src/Engine/graphics_engine/resource_manager/resource_manager.i"
	@echo "... src/Engine/graphics_engine/resource_manager/resource_manager.s"
	@echo "... src/Engine/graphics_engine/resource_manager/texture_manager/texture.o"
	@echo "... src/Engine/graphics_engine/resource_manager/texture_manager/texture.i"
	@echo "... src/Engine/graphics_engine/resource_manager/texture_manager/texture.s"
	@echo "... src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.o"
	@echo "... src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.i"
	@echo "... src/Engine/graphics_engine/resource_manager/texture_manager/texture_manager.s"
	@echo "... src/Engine/graphics_engine/swapchain/swapchain.o"
	@echo "... src/Engine/graphics_engine/swapchain/swapchain.i"
	@echo "... src/Engine/graphics_engine/swapchain/swapchain.s"
	@echo "... src/Engine/graphics_engine/vertex_buffer/vertex_buffer.o"
	@echo "... src/Engine/graphics_engine/vertex_buffer/vertex_buffer.i"
	@echo "... src/Engine/graphics_engine/vertex_buffer/vertex_buffer.s"
	@echo "... src/Engine/graphics_engine/vertex_shader/vertex_shader.o"
	@echo "... src/Engine/graphics_engine/vertex_shader/vertex_shader.i"
	@echo "... src/Engine/graphics_engine/vertex_shader/vertex_shader.s"
	@echo "... src/Engine/input_system/input_system.o"
	@echo "... src/Engine/input_system/input_system.i"
	@echo "... src/Engine/input_system/input_system.s"
	@echo "... src/Engine/physics/physics.o"
	@echo "... src/Engine/physics/physics.i"
	@echo "... src/Engine/physics/physics.s"
	@echo "... src/Engine/windowing/window.o"
	@echo "... src/Engine/windowing/window.i"
	@echo "... src/Engine/windowing/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

